version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@babel/core"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.10.1
    - 3.8.3
    - 3.9.0
    - 3.9.1
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
    - 4.5.0
  - dependency-name: webpack
    versions:
    - 4.46.0
    - 5.28.0
  - dependency-name: spdx-license-list
    versions:
    - 6.4.0
  - dependency-name: "@babel/plugin-transform-runtime"
    versions:
    - 7.12.15
    - 7.12.17
    - 7.13.10
    - 7.13.8
    - 7.13.9
  - dependency-name: "@babel/runtime"
    versions:
    - 7.12.13
    - 7.12.18
    - 7.13.10
    - 7.13.8
    - 7.13.9
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.10
    - 7.13.8
    - 7.13.9
  - dependency-name: webpack-dev-server
    versions:
    - 3.11.2
